#!/usr/bin/env python3
"""Merge docker-compose.yml with add-on files into ONE compose file for Portainer.

Portainer deploys a single file, so add-ons (docker-compose.<name>.yml) must be
merged first. ${VARS} are kept as-is (Portainer fills them from the stack's
environment variables). `docker compose config --no-interpolate` can't be used
for this: it rewrites bind mounts as named volumes.

    scripts/portainer-config.py nvidia vpn > portainer-stack.yml

Implements the parts of Compose's merge rules these files use: mappings merge,
`environment` lists merge by variable name, other lists append without
duplicates, and `!reset` removes a key.
"""
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
RESET = object()


class Loader(yaml.SafeLoader):
    pass


Loader.add_constructor("!reset", lambda loader, node: RESET)


def env_key(item):
    return str(item).split("=", 1)[0]


def merge(base, over, key=None):
    if over is RESET:
        return RESET
    if isinstance(base, dict) and isinstance(over, dict):
        out = dict(base)
        for k, v in over.items():
            merged = merge(out.get(k), v, k) if k in out else v
            if merged is RESET:
                out.pop(k, None)
            else:
                out[k] = merged
        return out
    if isinstance(base, list) and isinstance(over, list):
        if key == "environment":
            keys = {env_key(i): i for i in base}
            keys.update({env_key(i): i for i in over})
            return list(keys.values())
        return base + [i for i in over if i not in base]
    return over


def strip_resets(node):
    if isinstance(node, dict):
        return {k: strip_resets(v) for k, v in node.items() if v is not RESET}
    return node


def main(addons):
    doc = yaml.load((ROOT / "docker-compose.yml").read_text(), Loader=Loader)
    for name in addons:
        path = ROOT / f"docker-compose.{name}.yml"
        if not path.exists():
            sys.exit(f"no such add-on: {path.name}")
        doc = merge(doc, yaml.load(path.read_text(), Loader=Loader))
    doc = strip_resets(doc)
    # A service that joins another's network can't also have its own networks
    for svc in doc.get("services", {}).values():
        if str(svc.get("network_mode", "")).startswith("service:"):
            svc.pop("networks", None)
            svc.pop("ports", None)
    print(f"# Generated by scripts/portainer-config.py {' '.join(addons)}. Do not edit; "
          "edit docker-compose*.yml and regenerate.")
    yaml.dump(doc, sys.stdout, Dumper=yaml.SafeDumper, sort_keys=False,
              default_flow_style=False, width=1000, allow_unicode=True)


if __name__ == "__main__":
    main(sys.argv[1:])
